qiniu/go-sdk

storage/bucket.go

feat(bucket): add the status field at FileInfo

---

client/client.go
client/header.go
client/header_test.go
conf/conf.go
storage/bucket_test.go

Add Header: X-Qiniu-Date

---

auth/credentials.go
auth/credentials_test.go
storage/pfop.go

https://jira.qiniu.io/browse/KODO-15985

Auth verify support Qiniu

---

storage/region.go
storage/region_uc_v2.go
storage/region_uc_v2_test.go
storage/region_uc_v4.go

https://jira.qiniu.io/browse/KODO-17377

uc query return io src domain

---

CHANGELOG.md
storage/bucket.go
storage/bucket_test.go

https://jira.qiniu.io/browse/KODO-17491

change bucket manager batch func

---

storage/bucket.go
storage/bucket_list.go

https://jira.qiniu.io/browse/KODO-17473

List bucket use v1

---

CHANGELOG.md
storage/bucket.go

issue：
https://jira.qiniu.io/browse/KODO-17679

BucketManager func change: BatchWithBucket -> BatchWithContext

---

qvs/stream.go

1，qvs静态模式添加playExpireSec字段；
2，qvs动态模式添加playExpireSec字段。

LINK-2757 qvs add playExpireSec

---

storage/bucket.go
storage/bucket_test.go
storage/buckets_v4.go
storage/uc.go

add BucketManager.SetRemark / BucketManager.BucketsV2

---

internal/clientv2/interceptor_retry_hosts_test.go
internal/clientv2/interceptor_retry_simple_test.go
storage/region.go
storage/region_uc_v2.go
storage/region_uc_v4.go
storage/uc.go

uc query api: backup host add api.qiniu.com

---

internal/clientv2/interceptor_retry_simple.go
storage/region.go
storage/region_test.go
storage/region_uc_v2_test.go
storage/zone.go

remove region: ap-northeast-1

---

internal/clientv2/client.go
internal/clientv2/interceptor_retry_simple.go
storage/region.go
storage/uc.go

Bucket manager uc client inner v1 client

---

.github/workflows/ci-test.yml
Makefile
client/client.go
doc.go
err.go
internal/clientv2/interceptor_debug.go
linking/device.go
rtc/util.go
storage/bucket.go
storage/bucket_test.go
storage/errs.go
storage/form_upload.go
storage/pfop.go
storage/region.go
storage/region_uc_v2.go
storage/region_uc_v4.go
storage/resume_uploader.go
storage/resume_uploader_base.go
storage/uploader_base.go
storage/util.go
types.go

将 staticcheck 作为 ci 检查内容

---

CHANGELOG.md

version to v7.19.1

---

CHANGELOG.md
README.md
conf/conf.go

bump version to v7.20.0

---

internal/clientv2/interceptor_retry_simple.go

handle request retry

---

.github/workflows/ci-test.yml
internal/clientv2/multipart.go
internal/clientv2/multipart_test.go
storage/form_upload.go
storagev2/apis/api_post_object.go
storagev2/http_client/multipart.go
storagev2/internal/api-generator/multipart.go

fix formUploader content-type bug

---

CHANGELOG.md
README.md
conf/conf.go

Bump version to v7.21.0

---

CHANGELOG.md
README.md
conf/conf.go

Bump version to v7.21.1

---

CHANGELOG.md
README.md

version to v7.25.2
